
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-03T13:43:54-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f7bf0fa56f312829ba08a4a65a6171ab0ca9e49",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
